from rest_framework import serializers

class RetoSerializer(serializers.Serializer):
    id_reto = serializers.IntegerField(read_only=True)
    nombre_reto = serializers.CharField(max_length=100)
    id_tema = serializers.IntegerField()
    descripcion = serializers.CharField()
    pregunta = serializers.CharField()
    img_reto = serializers.ImageField(required=False, allow_null=True, default=None)
    recompensa_monedas = serializers.IntegerField()
    costo_monedas = serializers.IntegerField()
    respuesta_uno = serializers.CharField(allow_blank=True, required=False)
    respuesta_dos = serializers.CharField(allow_blank=True, required=False)
    respuesta_tres = serializers.CharField(allow_blank=True, required=False)
    respuesta_cuatro = serializers.CharField(allow_blank=True, required=False)
    respuestaCorrecta = serializers.CharField(max_length=100)

class RetoCreateUpdateSerializer(serializers.Serializer):
    nombre_reto = serializers.CharField(max_length=100)
    id_tema = serializers.IntegerField()
    descripcion = serializers.CharField()
    pregunta = serializers.CharField()
    img_reto = serializers.ImageField(required=False, allow_null=True, default=None)
    recompensa_monedas = serializers.IntegerField()
    costo_monedas = serializers.IntegerField()
    respuesta_uno = serializers.CharField(allow_blank=True, required=False)
    respuesta_dos = serializers.CharField(allow_blank=True, required=False)
    respuesta_tres = serializers.CharField(allow_blank=True, required=False)
    respuesta_cuatro = serializers.CharField(allow_blank=True, required=False)
    respuestaCorrecta = serializers.CharField(max_length=100)